openshift_deployment_type: openshift-enterprise

openshift_release: '3.10'
openshift_version: '3.10.111'
openshift_image_tag: v3.10.111

openshift_master_default_subdomain: "{{ hostvars[groups['nodes'][1]].public_ip }}.xip.io"

openshift_ip: "{{ private_ip }}"
openshift_public_hostname: "{{ public_ip }}"
openshift_public_ip: "{{ public_ip }}"

openshift_disable_check: memory_availability,disk_availability,docker_storage

openshift_logging_install_logging: false
openshift_hosted_prometheus_deploy: false
openshift_hosted_manage_registry: false
openshift_enable_service_catalog: false
openshift_management_install_management: false

openshift_master_identity_providers:
- name: allow_all
  login: 'true'
  challenge: 'true'
  kind: AllowAllPasswordIdentityProvider