- hosts: all
  gather_facts: false
  roles:
  - shared-hosts-file

- hosts: all
  gather_facts: false
  roles:
  - rhsm_repositories
  vars:
    rhsm_repositories_enabled:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-ose-3.10-rpms
    - rhel-7-server-ansible-2.4-rpms

- hosts: all
  gather_facts: false
  tasks:
  - name: add openshift bin dir to system-wide $PATH for cli usage
    copy:
      dest: /etc/profile.d/openshift-path.sh
      content: 'PATH=$PATH:/usr/local/bin'

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- hosts: masters[0]
  gather_facts: false
  roles:
    - openshift_permissions
  tags:
    - openshift_permissions
